config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :lists do
  	resources :list_items
  end

  root 'lists#index'
end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
	belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :lists
	has_many :list_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
	before_action :find_list, only: [:create]

	def create

		@list_item = @list.list_items.create(list_item_params)

		if @list_item.save
			redirect_to :back
		else
			render 'new'
		end

	end


	private
	def list_item_params
		params.require(:list_item).permit(:title)
	end

	def find_list
		@list = List.find(params[:list_id])
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :find_list, only: [:edit, :show, :update, :destroy]

	def index
		@lists = List.all
	end

	def new
		@list = current_user.lists.build
	end

	def create
		@list = current_user.lists.create (list_params)
		if @list.save
			redirect_to @list
		else
			render 'new'
		end
	end

	def show
		
	end

	def edit
	end

	def update
		if @list.update (list_params)
			redirect_to @list
		else
			render 'edit'
		end
	end

	def destroy
		@list.delete
		redirect_to root_path
	end

	private
	def list_params
		params.require(:list).permit(:title, :description)
	end

	def find_list
		@list = List.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "ListBox", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New List", new_list_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
 
 	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
<%= yield %>

</body>
</html>

app/views/lists/_list_item.html.erb
<%= @list_item.title %>

app/views/lists/_list_item_form.html.erb
<%= simple_form_for ([@list, @list.list_items.build]) do |f| %>
	<%= f.input :title, label: false, placeholder: "Enter Task Item" %>
<% end %>

app/views/lists/_new_list_form.html.erb
<%= simple_form_for @list do |f| %>

	<%= f.input :title %>
	<%= f.input :description %>

	<%= f.button :submit %>

<% end %>

app/views/lists/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h2>Edit List</h2>
			<%= simple_form_for @list do |f| %>

				<%= f.input :title %>
				<%= f.input :description %>

				<%= f.button :submit %>

			<% end %>

		</div>
	</div>
</div>

app/views/lists/index.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-6 col-md-offset-3">
			
			<% @lists.each do |list| %>
				<div class="well list-box">
					<%= link_to list.title, list_path(list) %> <span class="created_by"><p>created by: <%= list.user.email %></p></span>
				</div>
			<% end %>

		</div>
	</div>
</div>


app/views/lists/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h3>New List</h3>
			
			<%= render 'lists/new_list_form' %>

		</div>
	</div>
</div>

app/views/lists/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h3><%= @list.title %>
			<%= link_to "Delete", @list, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
			<%= link_to "Edit", edit_list_path, class: "btn btn-xs btn-warning" %>
			</h3>
			<p><%= @list.description %></p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'lists/list_item_form' %>
			<%= @list.list_items.each do |item| %>
				<%= item.title %>
			<% end %>
		</div>
	</div>
</div>